schedule_template = [
    {'hour': '0', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '1', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '2', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '3', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '4', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '5', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '6', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '7', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '8', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '9', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '10', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '11', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '12', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '13', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '14', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '15', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '16', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '17', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '18', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '19', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '20', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '21', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '22', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'},
    {'hour': '23', 'total_ct': '0', 'total_amt': '$0', 'new_ct': '0', 'new_amt': '$0'}
]
